import {createBuiltInSystemPrompt} from '../context/system-prompt';
import {
  createAskUserQuestionsCancelledResult,
  createAskUserQuestionsFailureResult,
  parseAskUserQuestionsToolCall
} from '../../tools/ask-user-questions-tool-handler';
import {throwIfAborted} from '../../types/agent';

import type {AgentExecutionMode, AgentInstruction, ProviderUsage} from '../../types/agent';
import type {GoalState} from '../../types/goal';
import type {SkillCatalogEntry} from '../../types/skill';
import type {AskUserQuestionsRequest, ToolCall, ToolExecutionResult} from '../../types/tool';
import type {CompactionState, TodoState, TranscriptRecord} from '../../types/transcript';

const RUNTIME_CONTEXT_NOTICE = 'Not a user request. Auto-Generated by the code. Use silently.';

type ExecuteUserQuestionToolOptions = {
  abortSignal?: AbortSignal; // 父运行的取消信号，回答返回后再次检查。
  executionMode: AgentExecutionMode; // 决定是否允许等待交互式回答。
  onRequest?: (call: ToolCall, request: AskUserQuestionsRequest) => void; // 由所属loop注入的请求生命周期观察入口。
  onResponse?: (call: ToolCall, result: ToolExecutionResult) => void; // 由所属loop注入的结果生命周期观察入口。
  onWaiting?: (call: ToolCall) => void; // 真正等待交互前发布瞬时活动。
  request?: (call: ToolCall, request: AskUserQuestionsRequest) => Promise<ToolExecutionResult> | ToolExecutionResult; // 交互式App桥接；缺失时按取消处理。
};

/**
 * 协调一次用户问题工具调用的解析、headless取消和回答等待。
 * 调用方注入生命周期与活动回调，本函数不持有主/子运行身份或提交transcript。
 */
async function executeUserQuestionToolCall(call: ToolCall, options: ExecuteUserQuestionToolOptions): Promise<ToolExecutionResult> {
  const parsed = parseAskUserQuestionsToolCall(call);
  if (!parsed.ok) {
    const result = createAskUserQuestionsFailureResult(call, parsed.message);
    options.onResponse?.(call, result);
    return result;
  }

  options.onRequest?.(call, parsed.value);
  if (options.executionMode.kind === 'headless' || !options.request) {
    const result = createAskUserQuestionsCancelledResult(call);
    options.onResponse?.(call, result);
    return result;
  }

  options.onWaiting?.(call);
  const result = await options.request(call, parsed.value);
  options.onResponse?.(call, result);
  throwIfAborted(options.abortSignal);
  return result;
}

type ProviderRecordOptions = {
  activeRecords: TranscriptRecord[]; // 进入本次 provider 请求的活跃记录区间。
  agentInstructions?: AgentInstruction[]; // 当前 cwd 适用且已按层级排序的项目指令。
  basePrompt?: string; // 用户 system prompt override;缺省使用内置主 prompt。
  compaction?: CompactionState; // 压缩状态;摘要非空时前置为带回读提示的 user 记录。
  cwd: string; // 注入 runtime environment 的工作目录。
  memoryPrompts?: string[]; // 当前请求动态解析的 user/agent memory sections。
  rolePrompt?: string; // 子 Agent 等隔离运行追加的明确角色边界 section。
  sandboxNote?: string; // bash 沙箱生效时的边界说明;缺省表示本次未包装沙箱。
  sessionJournalPath?: string; // 会话 journal 路径;压缩摘要附带完整历史回读提示。
  skillCatalog?: SkillCatalogEntry[]; // 当前 revision 的有界 enabled skill 目录。
  todoState?: TodoState; // 待办状态;存在 open 项时追加 runtime context 后缀记录。
  goalState?: GoalState; // 常驻目标;存在时追加 runtime context 后缀记录。
};

/**
 * 构造 provider请求上下文；函数只投影输入事实，不判断主/子运行身份或提交 callback。
 */
function buildProviderRecords(options: ProviderRecordOptions): TranscriptRecord[] {
  const {activeRecords, agentInstructions = [], basePrompt, compaction, cwd, goalState, memoryPrompts = [], rolePrompt, sandboxNote, sessionJournalPath, skillCatalog = [], todoState} = options;
  const prefix: TranscriptRecord[] = [{
    role: 'system',
    text: createBuiltInSystemPrompt({agentInstructions, basePrompt, cwd, ...(sandboxNote ? {sandboxNote} : {}), skillCatalog, memoryPrompts, rolePrompt})
  }];

  if (compaction && compaction.summaryText.trim() !== '') {
    const summaryText = `Here is a structured summary of the earlier conversation:\n${compaction.summaryText}`;
    prefix.push({
      role: 'user',
      text: sessionJournalPath
        ? [
            summaryText,
            '',
            `The full original history is preserved in source_file: ${sessionJournalPath}`,
            'If exact details are needed, use the existing read_files tool to read source_file with pagination.',
            'source_file is an append-only JSONL journal; later truncate or set operations can supersede earlier entries.'
          ].join('\n')
        : summaryText
    });
  }

  return [
    ...prefix,
    ...activeRecords.filter((record) => record.role !== 'subagent' && record.role !== 'reasoning_summary'),
    ...createRuntimeContextSuffixRecords(todoState, goalState)
  ];
}

function createRuntimeContextSuffixRecords(todoState: TodoState | undefined, goalState: GoalState | undefined): TranscriptRecord[] {
  const sections = createGoalSectionLines(goalState);
  const openTodos = (todoState?.items || []).filter((item) => item.status === 'open');

  if (openTodos.length > 0) {
    sections.push('## Todos', 'Open:', ...openTodos.map((item) => `- [${item.id}] ${item.text}`));
  }

  if (sections.length === 0) {
    return [];
  }

  return [{
    role: 'user',
    text: [
      '# Echo Runtime Context',
      '',
      RUNTIME_CONTEXT_NOTICE,
      '',
      ...sections
    ].join('\n')
  }];
}

/**
 * 把当前 goal 投影为 runtime context 的 Goal section；未设置目标时返回空数组。
 * active 目标提示继续按条件推进，paused 目标明确等待用户恢复、不得自动继续。
 */
function createGoalSectionLines(goalState: GoalState | undefined): string[] {
  if (!goalState) {
    return [];
  }

  const statusLine = goalState.status === 'active'
    ? `Status: active; continuation turn ${goalState.turns}/${goalState.maxTurns}. Work toward the objective; an independent evaluator judges whether it is met after each turn.`
    : 'Status: paused; waiting for the user to resume. Do not continue working toward the objective automatically.';

  return [
    '## Goal',
    `Objective: ${goalState.condition}`,
    statusLine,
    ...(goalState.lastEvaluation ? [`Last evaluation: ${goalState.lastEvaluation.outcome} — ${goalState.lastEvaluation.reason}`] : [])
  ];
}

function hasRecordableProviderUsage(usage: ProviderUsage | undefined, usageInputTokens: number | undefined): boolean {
  return (
    typeof usageInputTokens === 'number' ||
    typeof usage?.inputTokens === 'number' ||
    typeof usage?.cacheCreationInputTokens === 'number' ||
    typeof usage?.cacheReadInputTokens === 'number' ||
    typeof usage?.outputTokens === 'number'
  );
}

export {
  buildProviderRecords,
  executeUserQuestionToolCall,
  hasRecordableProviderUsage
};

export type {ExecuteUserQuestionToolOptions, ProviderRecordOptions};
