import {buildProviderRequestPrefix} from '../context/provider-request-prefix';
import {
  createAskUserQuestionsCancelledResult,
  createAskUserQuestionsFailureResult,
  parseAskUserQuestionsToolCall
} from '../../tools/ask-user-questions-tool-handler';
import {throwIfAborted} from '../../types/agent';

import type {AgentExecutionMode, ProviderUsage} from '../../types/agent';
import type {AskUserQuestionsRequest, ToolCall, ToolExecutionResult} from '../../types/tool';
import type {ProviderRequestPrefixOptions} from '../context/provider-request-prefix';
import type {TodoState, TranscriptRecord} from '../../types/transcript';

const RUNTIME_CONTEXT_NOTICE = 'Not a user request. Auto-Generated by the code. Use silently.';

type ExecuteUserQuestionToolOptions = {
  abortSignal?: AbortSignal; // 父运行的取消信号，回答返回后再次检查。
  executionMode: AgentExecutionMode; // 决定是否允许等待交互式回答。
  onRequest?: (call: ToolCall, request: AskUserQuestionsRequest) => void; // 由所属loop注入的请求生命周期观察入口。
  onResponse?: (call: ToolCall, result: ToolExecutionResult) => void; // 由所属loop注入的结果生命周期观察入口。
  onWaiting?: (call: ToolCall) => void; // 真正等待交互前发布瞬时活动。
  request?: (call: ToolCall, request: AskUserQuestionsRequest) => Promise<ToolExecutionResult> | ToolExecutionResult; // 交互式App桥接；缺失时按取消处理。
};

/**
 * 协调一次用户问题工具调用的解析、headless取消和回答等待。
 * 调用方注入生命周期与活动回调，本函数不持有主/子运行身份或提交transcript。
 */
async function executeUserQuestionToolCall(call: ToolCall, options: ExecuteUserQuestionToolOptions): Promise<ToolExecutionResult> {
  const parsed = parseAskUserQuestionsToolCall(call);
  if (!parsed.ok) {
    const result = createAskUserQuestionsFailureResult(call, parsed.message);
    options.onResponse?.(call, result);
    return result;
  }

  options.onRequest?.(call, parsed.value);
  if (options.executionMode.kind === 'headless' || !options.request) {
    const result = createAskUserQuestionsCancelledResult(call);
    options.onResponse?.(call, result);
    return result;
  }

  options.onWaiting?.(call);
  const result = await options.request(call, parsed.value);
  options.onResponse?.(call, result);
  throwIfAborted(options.abortSignal);
  return result;
}

type ProviderRecordOptions = ProviderRequestPrefixOptions & {
  activeRecords: TranscriptRecord[]; // 进入本次 provider 请求的活跃记录区间。
  todoState?: TodoState; // 待办状态;存在 open 项时追加 runtime context 后缀记录。
};

/**
 * 构造 provider请求上下文；前导复用共享构造，函数只投影输入事实，不判断主/子运行身份或提交 callback。
 */
function buildProviderRecords(options: ProviderRecordOptions): TranscriptRecord[] {
  const {activeRecords, todoState, ...prefixOptions} = options;

  return [
    ...buildProviderRequestPrefix(prefixOptions),
    ...activeRecords.filter((record) => record.role !== 'subagent' && record.role !== 'reasoning_summary'),
    ...createRuntimeContextSuffixRecords(todoState)
  ];
}

function createRuntimeContextSuffixRecords(todoState: TodoState | undefined): TranscriptRecord[] {
  const openTodos = (todoState?.items || []).filter((item) => item.status === 'open');
  if (openTodos.length === 0) {
    return [];
  }

  return [{
    role: 'user',
    text: [
      '# Echo Runtime Context',
      '',
      RUNTIME_CONTEXT_NOTICE,
      '',
      '## Todos',
      'Open:',
      ...openTodos.map((item) => `- [${item.id}] ${item.text}`)
    ].join('\n')
  }];
}

function hasRecordableProviderUsage(usage: ProviderUsage | undefined, usageInputTokens: number | undefined): boolean {
  return (
    typeof usageInputTokens === 'number' ||
    typeof usage?.inputTokens === 'number' ||
    typeof usage?.cacheCreationInputTokens === 'number' ||
    typeof usage?.cacheReadInputTokens === 'number' ||
    typeof usage?.outputTokens === 'number'
  );
}

export {
  buildProviderRecords,
  executeUserQuestionToolCall,
  hasRecordableProviderUsage
};

export type {ExecuteUserQuestionToolOptions, ProviderRecordOptions};
