import {createBuiltInSystemPrompt} from '../context/system-prompt';

import type {AgentInstruction, ProviderUsage} from '../../types/agent';
import type {SkillCatalogEntry} from '../../types/skill';
import type {ToolExecutionResult} from '../../types/tool';
import type {CompactionState, TodoState, TranscriptRecord} from '../../types/transcript';

const RUNTIME_CONTEXT_NOTICE = 'Not a user request. Auto-Generated by the code. Use silently.';

/**
 * 构造 provider请求上下文；函数只投影输入事实，不判断主/子运行身份或提交 callback。
 */
function buildProviderRecords(activeRecords: TranscriptRecord[], cwd: string, compaction?: CompactionState, skillCatalog: SkillCatalogEntry[] = [], agentInstructions: AgentInstruction[] = [], todoState?: TodoState, memoryPrompts: string[] = [], basePrompt?: string, sessionJournalPath?: string, rolePrompt?: string): TranscriptRecord[] {
  const prefix: TranscriptRecord[] = [{
    role: 'system',
    text: createBuiltInSystemPrompt({agentInstructions, basePrompt, cwd, skillCatalog, memoryPrompts, rolePrompt})
  }];

  if (compaction && compaction.summaryText.trim() !== '') {
    const summaryText = `Here is a structured summary of the earlier conversation:\n${compaction.summaryText}`;
    prefix.push({
      role: 'user',
      text: sessionJournalPath
        ? [
            summaryText,
            '',
            `The full original history is preserved in source_file: ${sessionJournalPath}`,
            'If exact details are needed, use the existing read_files tool to read source_file with pagination.',
            'source_file is an append-only JSONL journal; later truncate or set operations can supersede earlier entries.'
          ].join('\n')
        : summaryText
    });
  }

  return [
    ...prefix,
    ...activeRecords.filter((record) => record.role !== 'subagent' && record.role !== 'reasoning_summary'),
    ...createRuntimeContextSuffixRecords(todoState)
  ];
}

function createRuntimeContextSuffixRecords(todoState: TodoState | undefined): TranscriptRecord[] {
  const openTodos = (todoState?.items || []).filter((item) => item.status === 'open');
  if (openTodos.length === 0) {
    return [];
  }

  return [{
    role: 'user',
    text: [
      '# Echo Runtime Context',
      '',
      RUNTIME_CONTEXT_NOTICE,
      '',
      '## Todos',
      'Open:',
      ...openTodos.map((item) => `- [${item.id}] ${item.text}`)
    ].join('\n')
  }];
}

function createProviderUsageDebugPayload(usage: ProviderUsage | undefined, usageInputTokens: number | undefined): ProviderUsage | null {
  const payload: ProviderUsage = {
    ...(typeof usageInputTokens === 'number' ? {inputTokens: usageInputTokens} : {}),
    ...(typeof usage?.inputTokens === 'number' ? {inputTokens: usage.inputTokens} : {}),
    ...(typeof usage?.cacheCreationInputTokens === 'number' ? {cacheCreationInputTokens: usage.cacheCreationInputTokens} : {}),
    ...(typeof usage?.cacheReadInputTokens === 'number' ? {cacheReadInputTokens: usage.cacheReadInputTokens} : {}),
    ...(typeof usage?.outputTokens === 'number' ? {outputTokens: usage.outputTokens} : {})
  };

  return Object.keys(payload).length > 0 ? payload : null;
}

function hasRecordableProviderUsage(usage: ProviderUsage | undefined, usageInputTokens: number | undefined): boolean {
  return (
    typeof usageInputTokens === 'number' ||
    typeof usage?.inputTokens === 'number' ||
    typeof usage?.cacheCreationInputTokens === 'number' ||
    typeof usage?.cacheReadInputTokens === 'number' ||
    typeof usage?.outputTokens === 'number'
  );
}

function isToolResultTruncated(result: ToolExecutionResult): boolean | undefined {
  switch (result.details.kind) {
    case 'glob':
    case 'grep':
    case 'read_files':
    case 'web_fetch':
    case 'web_search':
    case 'bash':
      return result.details.truncated;
    case 'apply_patch':
    case 'edit_file':
    case 'generic':
      return undefined;
  }
}

export {
  buildProviderRecords,
  createProviderUsageDebugPayload,
  hasRecordableProviderUsage,
  isToolResultTruncated
};
